CREATE DATABASE IF NOT EXISTS PupsNPoodles;

use PupsNPoodles;

CREATE USER IF NOT EXISTS 'databaseUser'@'localhost' IDENTIFIED BY 'user123';

GRANT ALL PRIVILEGES ON PupsNPoodles.* TO databaseUser@localhost;

CREATE TABLE IF NOT EXISTS UserTable (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(25) NOT NULL,
username VARCHAR(25) NOT NULL,
password VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS PetTable (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(25) NOT NULL,
age INT,
ownerId INT NOT NULL
)